config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'books'=> 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  get 'top' => 'books#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end


  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
      flash[:alert] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:alert] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:alert] = "Book was successfully destroyed."
    redirect_to books_path
  end



  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>




<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |f| %>

<div class="field">Title</div>
<%= f.text_field :title %>
<div class="field">Body</div>
<%= f.text_area :body %>

<div><%= f.submit 'Update Book' %></div>

<div><%= link_to "show", book_path(@book.id) %>
<%= link_to "back", books_path %></div>

<% end %>

app/views/books/index.html.erb
<p id="alert"><%= alert %></p>

<h1>Books</h1>
<table>
<thead>
<tr><th>Title</th>
<th>Body</th>
<th colspan="3"></th></tr>
</thead>



<tbody>
<tr><% @books.each do |book| %>
<td><%= book.title %></td>
<td><%= book.body %></td>
<td><%= link_to "show", book_path(book.id) %></td>
<td><%= link_to "edit", edit_book_path(book.id) %></td>
<td><%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td></tr></tbody>

<% end %></table>







<h3>New book</h3>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: Book.new, local:true do |f| %>
  <div class="field">Title</div>
  <%= f.text_field :title %>

  <div class="field">Body</div>
  <%= f.text_area :body %>

  <div class="actions"><%= f.submit 'Create Book' %></div>
 <% end %>

app/views/books/show.html.erb
<p id="alert"><%= alert %></p>

<p><strong>Title:</strong><%= @book.title %></p>

<p><strong>Body:</strong><%= @book.body %></p>



<%= link_to "edit", edit_book_path(@book.id) %>
<%= link_to "back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>

<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>